service: videolyzer

provider:
  name: aws
  runtime: python3.6
  profile: ${file(../config.${self:provider.stage}.json):videolyzer.profile}

functions:
  startProcessingVideo:
    handler: handler.start_processing_video
    events:
      - s3:
          bucket: ${file(../config.${self:provider.stage}.json):videolyzer.videos_bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .mp4
